In [ ]:
import numpy as np
e=np.ones((8,4))
print(e)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
A=np.random.rand(1)
print(A)

[0.86061439]


random module is the sub package of numpy

In [ ]:
B=np.random.rand(8,4) #rand range is betweem 0 to 1
print(B)

[[0.04655319 0.22521403 0.60777125 0.49725721]
 [0.24935852 0.40439836 0.95935947 0.76777222]
 [0.30574817 0.96014328 0.07254355 0.61454   ]
 [0.3879074  0.13559406 0.47969036 0.06831804]
 [0.45597684 0.72065482 0.48980114 0.30623236]
 [0.03422658 0.84389017 0.31470213 0.30223657]
 [0.98203716 0.03767817 0.60795655 0.3551125 ]
 [0.24724346 0.22287372 0.59892013 0.83348055]]


In [ ]:
B=10*np.random.rand(8,4) #rand range is betweem 0 to 1
print(B)

[[5.48967627 4.1779676  8.90030235 9.17160775]
 [1.09010566 0.33831855 1.54594485 0.95578948]
 [3.10255466 6.62906067 7.25858498 9.86780243]
 [4.27818228 8.33867261 9.80659958 1.80826685]
 [9.56150181 0.89569454 1.86597298 0.62607036]
 [7.97484847 3.15294896 6.17839246 2.42915632]
 [0.02177635 7.6515156  6.8282518  4.63042893]
 [2.9164385  0.37338033 4.95667933 7.99078115]]


In [ ]:
B=np.floor(8.2) #rand range is betweem 0 to 1
print(B)

8.0


In [ ]:
c=np.arange(1,33).reshape(8,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(c,4)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(c,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(c,(3,5)) #spilt it after 3rd row and 5th row


[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
E=np.arange(1,33).reshape(4,8)
print(E)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(E,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(E,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

trigonometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
d=np.rad2deg(A)
print(d)

[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(A)
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.sin(1) #radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.var(st)  #varance=std square

597.9166666666666

In [ ]:
np.std(st) #difference from mean to each element and sum of all differences divided by no.of abservations

24.452334585202017

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


numpy one of the sub package is linear algebra=linalg

In [ ]:
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
D=np.arange(1,22).reshape(3,7)
print(D)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [ ]:
D=10*np.random.rand(21).reshape(3,7)
print(D)

[[7.2741412  9.37582263 5.72526158 0.21125446 2.416311   6.1054072
  5.92465126]
 [5.96271786 9.0337596  5.56233103 1.75917351 7.66024809 1.52807554
  2.17832092]
 [7.51629592 5.21506046 6.21966832 9.84632186 3.38157163 8.80577576
  7.57341274]]


In [ ]:
print(np.argmax(D)) #index position of max

17


In [ ]:
print(np.argmax(D,axis=0)) #COLUMN WISE INDEX POSITION MAX

[2 0 2 2 1 2 2]


In [ ]:
print(np.argmax(D,axis=1))  #ROW  wise INDEX POSITION MAX

[1 1 3]


In [ ]:
print(np.argmin(D))

3


In [ ]:
print(np.argmin(D,axis=0))   #coloumn wise index position min

[1 2 1 0 0 1 1]


In [ ]:
print(np.argmin(D,axis=1))   #row wise index position min

[3 5 4]


searching

In [ ]:
a=np.array([34,56,7,17,88,91])  #indexpositions of numbers divisible by 2
print(np.where(a%2==0))


(array([0, 1, 4]),)


In [ ]:
m=np.array([24,16,7,17,54,60])
print(np.where(m%6==0))

(array([0, 4, 5]),)


In [ ]:
s=np.array([1,2,3,5,8]) #applicable only for sorted list
X=np.searchsorted(s,5)
print(X)

3


sorting

In [ ]:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


2d array happens with rows

In [ ]:
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


filter

In [ ]:
arr=np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]

array([40, 50, 44, 78])

iterating through two arrays

In [ ]:
names=np.array(["veena","kav","kus","tej","varsh","sadha"])
initials=np.array(["J","T","B","E","V","M"])
for i,j in zip(initials,names):
  print(i,".",j)

J . veena
T . kav
B . kus
E . tej
V . varsh
M . sadha


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,2,20,25,25])
n=np.divide(a1,a2)
print(n)

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,2,20,25,25])
n=np.mod(a1,a2)
print(n)

[10  0  0  0  0 10]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,2,20,25,25])
n=np.divmod(a1,a2)
print(n)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


logarithms

In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log2(a1))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
a=1.2
print(np.log(a))

0.1823215567939546


In [ ]:
a=1.2
print(np.log10(a))  #base10

0.07918124604762482


In [ ]:
a=np.array([1,1.2,3,4])
print(np.log(a))


[0.         0.18232156 1.09861229 1.38629436]


other mathmetical functions

In [ ]:
a2=np.array([5,6,7,10]) #cumilativeproduct
x=np.cumprod(a2)
print(x)

[   5   30  210 2100]


In [ ]:
a2=np.array([5,6,7,10])
x=np.cumsum(a2)
print(x)

[ 5 11 18 28]


In [ ]:
a3=np.array([10,15,25,15])
newarr=np.diff(a3) #difference element2-element1
print(newarr)

[  5  10 -10]


In [ ]:
num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1=455
num2=665
x=np.gcd(num1,num2)
print(x)

35


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a) #takes multiple inputs gives single output
print(gc)

3


In [ ]:
a=np.array([12,15,60])
lc=np.lcm.reduce(a) #takes multiple inputs gives single output
print(lc)

60
